# apiVersion : v1
# kind: Pod
# metadata:
#   name: emptydir
#   labels: 
#     app : k8s-application
#     env: practice-room
#     owner: dos11-student
#     project: dos11
# spec:
#   containers:
#     - name: container-nginx
#       image: kpk666/docker_practice:nginx1.23.3
#       ports:
#         - containerPort: 80
#       volumeMounts:
#         - name: emptydir
#           mountPath: /var/www/html
#   volumes:
#     - name: emptydir
#       emptyDir: {}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: emptydir
  labels:
    app : k8s-application
    env: practice-room
    owner: dos11-student
    project: dos11
spec: 
  replicas: 2
  selector:
    matchLabels:
      project: dos11
  template:
    metadata:
      labels:
        project: dos11
    spec:
      containers:
        - name : emptydir
          image: kpk666/docker_practice:nginx1.23.3
          ports:
           - containerPort: 80
          volumeMounts:
            - name: emptydir
              mountPath: /var/www/html
      volumes:
        - name: emptydir
          emptyDir: {}
             

---
apiVersion: v1
kind: Service
metadata:
  name: my-service-nordport
  labels: 
    env: practice
    owner: dos11-student
spec:
  selector:
    project: dos11
  type: NodePort
  ports:
  - name: my-service-nordport
    protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30666
