apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
  labels:
    app : k8s-application
    env: practice-room
    owner: dos11-student
    project: dos11
spec:
  containers:
  - image: kpk666/docker_practice:latest
    name: test-container
    volumeMounts:
    - mountPath: /home
      name: test-home-path
  volumes:
  - name: test-home-path
    hostPath:
      path: /data      
      type: Directory
             
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-nordport
  labels: 
    env: practice
    owner: dos11-student
spec:
  selector:
    project: dos11
  type: NodePort
  ports:
  - name: my-service-nordport
    protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30666
