apiVersion: v1
kind: Pod
metadata:
  name: my-secret-pod
  namespace: default
  labels:
    app : k8s-application
    env: practice-room
    owner: dos11-student
    project: dos11
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: mysecret
  containers:
  - name: my-secrect-pod
    image: registry.k8s.io/busybox    
    command: ["/bin/sh", "-c", env]
    envFrom: 
    - secretRef:
        name: mysecret
  restartPolicy: Never

---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  USER_NAME: VXNlckZvclBvZA==
  PASSWORD: TXlwYXNzd29yZEZvclBvZA==
          
