apiVersion: batch/v1
kind: Job
metadata:
  name: my-own-pi
spec:
  template:
    spec:
      containers:
      - name: my-onw-pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4