apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.network.name }}
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "mysql.labels" . | nindent 6 }}      
  policyTypes:
    - {{ .Values.network.policytype}}
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            namespace: {{ .Values.namespace }}
      - podSelector:
          matchLabels:
            app: {{ .Release.Name }}              
      ports:
        - protocol: {{ .Values.mysql.service.protocol}}
          port: {{ .Values.mysql.service.port}} 