apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "wordpress.pvc" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.wordpress.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.wordpress.pvc.storage }}
