namespace: dev

wordpress:
    deployment:
        image: wordpress:4.8-apache        
    service:
        type: NodePort
        port: 80
        nodeport: 30666
    pvc:
        accessMode: ReadWriteOnce
        storage: 8Gi

mysql:
    deployment:
        image: mysql:5.6        
    service:
        type: ClusterIP
        port: 3306
        protocol: TCP
    pvc:
        accessMode: ReadWriteOnce
        storage: 2Gi


autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: wordpress.local
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: mysql.local
      paths:
        - path: /
          pathType: ImplementationSpecific      
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

network:
  name: network-policy
  policytype: Ingress
  port: 80

resources: 
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 100Mi

nodeSelector: {}