apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: dev
  labels:
    app: wordpress
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
    nodePort: 30666